branch-defaults:
  create_contact:
    environment: Prtest-env
    group_suffix: null
global:
  application_name: pr_Test
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2
  default_region: ap-northeast-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
