# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: cimg/php:8.4
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: sail
          MYSQL_DATABASE: type_89
          MYSQL_PASSWORD: 'password'
          MYSQL_HOST: 127.0.0.1

    steps:
      - checkout
      - run:
          name: Install PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev
            sudo docker-php-ext-install zip bcmath pdo_mysql

      # composer cache
      - restore_cache:
          keys:
            - composer-v2-{{ checksum "composer.lock" }}
            - composer-v2-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # prepare the database
      - run: php artisan migrate --env=testing --database=mysql --force
      - run: ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
      - run: ./vendor/bin/phpcs --standard=phpcs.xml ./
      - run: ./vendor/bin/phpstan analyse --memory-limit=2G
      - run: ./vendor/bin/phpmd . text phpmd.xml
      - run: ./vendor/bin/phpunit --coverage-html /tmp/build/coverage
      - store_artifacts:
          path: /tmp/build
          destination: build

workflows:
  version: 2
  workflow:
    jobs:
      - test
